apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: amt-astronaut-slackbot
  namespace: amt
  labels:
    team: amt
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - https://amt-astronaut-slackbot.nav.no
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
    - name: PORT
      value: "3000"
    - name: SLASH_COMMAND
      value: "/astronaut"
  envFrom:
    - secret: amt-astronaut-slackbot
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: amt-astronaut-slackbot-db
