name: Deploy to dev-gcp

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and deploy to dev-gcp
    runs-on: ubuntu-latest
    environment: dev-gcp
    concurrency:
      group: deploy-dev-gcp
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build and push container image
        id: image
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        with:
          team: amt
          dockerfile: Dockerfile
          tag: ${{ github.sha }}

      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ steps.image.outputs.image }}
